Create use case for the take turn.
CSC207-2022F-UofT/course-project-scramblers pull request #62
Opened 2022-11-29 16:29 UTC by minaccchiang

Need two more method for presenter.

still need exchange letter to finish take turn interactor

have not check if the word is valid (mojan's user story)

2022-11-29 18:10 UTC, JosephSun2003 commented on src/main/java/Take_Turn/TakeTrunInputData.java
> +        this.gameState = gameState;
Isn't requried since gameState is static.

2022-11-29 18:13 UTC, JosephSun2003 requested changes
Overall, everything should work, a few changes to references to gameState since we can call it from as GameState.methodName();

2022-11-30 21:03 UTC, JosephSun2003 commented
MERGE ONLY AFTE HRID's Changes are MERGED.

2022-11-30 21:04 UTC, JosephSun2003 submitted a review, later dismissed
Changes look good. No concerns noticed.

2022-12-01 15:14 UTC, ethanhonest reviewed
The inputData should be passed as parameter to taketurn() as opposed to in the constructor. I will create the constructor in main, so I won't know what to pass in until the user manually puts in their instructions. So, please remove inputData as a parameter from the constructor, and add it as a parameter to taketurn().

Otherwise, looks good, and I will approve once that change is made

2022-12-01 16:53 UTC, JosephSun2003 approved these changes
Code looks good, aside from Ethan's comment, everything looks fine.

2022-12-02 16:50 UTC, JosephSun2003 commented
Resolved the conflicts with main, mostly minor things.

2022-12-02 21:10 UTC, JosephSun2003 approved these changes
Overall, merging went nicely since most of the code were repeats of one another.

2022-12-03 00:32 UTC, ethanhonest approved these changes
Looks like there are minor typos in the names of the files, but overall the code looks good

2022-12-03 22:08 UTC, patelhrid approved these changes
Looks good to me.

2022-12-03 22:08 UTC, merged